openapi: 3.0.0
info:
  title: proyek3
  version: 1.0.0
servers:
  - url: https://be-3.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: payment
  - name: custom
paths:
  /api/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: patir
                email: fathir080604@gmail.com
                password: siganteng
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: fathir080604@gmail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/tambah-emas:
    post:
      tags:
        - auth
      summary: post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: emas 10000 gram
                karatan: 100
                berat: 19
                harga: 150000500
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /protected/emas:
    get:
      tags:
        - auth
      summary: get all
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /protected/emas/update/:
    put:
      tags:
        - auth
      summary: New Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: emas 1 gram
                karatan: 100
                berat: 19
                harga: 150000500
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/payment:
    post:
      tags:
        - payment
      summary: payment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                gross_amount: 5000000
                customer_details:
                  first_name: Fathir
                  email: fathir080604@gmail.com
                  phone: '08953319342686'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/orders:
    get:
      tags:
        - custom
      summary: Get All Order
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - custom
      summary: Add Order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                jenis_perhiasan: Gelang
                jenis_emas: Emas 24KK
                berat_emas: 10.5
                campuran_tambahan: Perak
                persentase_emas: 90
                total_harga: 5000000
      security:
        - bearerAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/protected/orders/98:
    get:
      tags:
        - custom
      summary: Get by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}